// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7gQdJ74sUZzftYUFHdkEK2O0QCBhRGAo',
    appId: '1:1034857993520:web:af02e876f028da253924f5',
    messagingSenderId: '1034857993520',
    projectId: 'fitnessaiapp-99781',
    authDomain: 'fitnessaiapp-99781.firebaseapp.com',
    storageBucket: 'fitnessaiapp-99781.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS24qN6XvsYGBaZDOxEa56XzWya2u2aaE',
    appId: '1:1034857993520:android:e2ec88c1278b10aa3924f5',
    messagingSenderId: '1034857993520',
    projectId: 'fitnessaiapp-99781',
    storageBucket: 'fitnessaiapp-99781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvh2v1LJUgi2cCbeYjuKPyueTInT9c7y0',
    appId: '1:1034857993520:ios:285bafda3230cdd93924f5',
    messagingSenderId: '1034857993520',
    projectId: 'fitnessaiapp-99781',
    storageBucket: 'fitnessaiapp-99781.appspot.com',
    iosBundleId: 'com.example.fitnessAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvh2v1LJUgi2cCbeYjuKPyueTInT9c7y0',
    appId: '1:1034857993520:ios:285bafda3230cdd93924f5',
    messagingSenderId: '1034857993520',
    projectId: 'fitnessaiapp-99781',
    storageBucket: 'fitnessaiapp-99781.appspot.com',
    iosBundleId: 'com.example.fitnessAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7gQdJ74sUZzftYUFHdkEK2O0QCBhRGAo',
    appId: '1:1034857993520:web:95817221d6ed721f3924f5',
    messagingSenderId: '1034857993520',
    projectId: 'fitnessaiapp-99781',
    authDomain: 'fitnessaiapp-99781.firebaseapp.com',
    storageBucket: 'fitnessaiapp-99781.appspot.com',
  );
}
